# Generated by Django 3.0 on 2024-05-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_alert', '0005_auto_20181103_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='givertransaction',
            name='userid',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
